[project]
protostar-version = "0.9.1"
lib-path = "lib"
cairo-path = ["lib", "./lib/starknetid", "./lib/cairo_contracts/src"]

[contracts]
whitelisted_sbt = ["src/presets/whitelisted_sbt.cairo"]
proxy = ["lib/cairo_contracts/src/openzeppelin/upgrades/presets/Proxy.cairo"]
